name: Auto Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    name: Auto Tag Assigner
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch

  build-and-release:
    name: Build Flatpak & Release
    needs: tag
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: vesper.flatpak
          manifest-path: io.github.TheRealShek.vesper.yml
          cache-key: flatpak-builder-${{ hashFiles('Cargo.lock', 'io.github.TheRealShek.vesper.yml') }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.tag.outputs.new_tag }}
          name: Release ${{ needs.tag.outputs.new_tag }}
          body: ${{ needs.tag.outputs.changelog }}
          files: vesper.flatpak
